name       : perl-file-find-rule
version    : 0.34
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RC/RCLAMP/File-Find-Rule-0.34.tar.gz : 7e6f16cc33eb1f29ff25bee51d513f4b8a84947bbfa18edb2d3cc40a2d64cafe
license    : GPL-2.0
component  : programming.perl
summary    : File::Find::Rule is a friendlier interface to File::Find.
description: |
    File::Find::Rule is a friendlier interface to File::Find.
rundeps    :
    - perl-number-compare
    - perl-text-glob
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
